"""
Code to create videos of images generated by the DCGAN
Implementation by Claudia Drygala, University of Wuppertal
"""

import cv2
import numpy as np
import glob
import os
from options.video_options import VideoOptions

# Parse the video options
opt = VideoOptions().parse()

DATA_PATH = opt.images_dir

img_array = []
print('Started to load the images...')
for root, dirs, files in os.walk(DATA_PATH):
    for file in files:
        if pix2pixHD: 
            if 'synthesized' in file:
                file_dir = os.path.join(DATA_PATH, file)        
                img = cv2.imread(file_dir)
                height, width, layers = img.shape
                size = (width, height)
                img_array.append(img)
        else:
            file_dir = os.path.join(DATA_PATH, file)        
            img = cv2.imread(file_dir)
            height, width, layers = img.shape
            size = (width, height)
            img_array.append(img)

# Make directory to save the videos
if opt.video_type == 'avi' or opt.video_type == 'mp4':
    SAVE_PATH = os.path.join('../videos', opt.video_type)
    if not os.path.exists(SAVE_PATH):
        os.makedirs(SAVE_PATH)
elif opt.video_type == 'both':
    SAVE_PATH_AVI = os.path.join('../videos', 'avi')
    if not os.path.exists(SAVE_PATH):
        os.makedirs(SAVE_PATH)
    SAVE_PATH_MP4 = os.path.join('../videos', 'mp4')
    if not os.path.exists(SAVE_PATH):
        os.makedirs(SAVE_PATH)
else:
    raise ValueError('Sorry, the video type is not known! Please choose one of the possible options: avi, mp4, both')

# Create and save videos
if opt.video_type == 'avi' or opt.video_type == 'mp4':
    print('Started to create an', opt.video_type, 'video...')
    save_file = os.path.join(SAVE_PATH, opt.video_name) + '_' + str(opt.fps) + 'fps.' + opt.video_type
    out = cv2.VideoWriter(save_file, cv2.VideoWriter_fourcc(*'M','J','P','G'), opt.fps, size)
    for i in range(len(img_array)):
        out.write(img_array[i])
    out.release()
else:
    print('Started to create an avi video...')
    save_file = os.path.join(SAVE_PATH, opt.video_name) + '_' + str(opt.fps) +  'fps.avi'
    out = cv2.VideoWriter(save_file, cv2.VideoWriter_fourcc(*'M','J','P','G'), opt.fps, size)
    for i in range(len(img_array)):
        out.write(img_array[i])
    out.release()
    print('Started to create a mp4 video...')
    save_file = os.path.join(SAVE_PATH, opt.video_name) + '_' + str(opt.fps) + 'fps.mp4'
    out = cv2.VideoWriter(save_file, cv2.VideoWriter_fourcc(*'M','J','P','G'), opt.fps, size)
    for i in range(len(img_array)):
        out.write(img_array[i])
    out.release()

print('Finished!')
